version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:40" # hh:mm formate
      timezone: "Australia/Perth"
      # set this limit to more than 0 to get this start working 
    open-pull-requests-limit: 0
    milestone: 2
    assignees:
      - "vvsrrSunny"
    reviewers:
     - "vvsrrSunny"
    ignore:
      # ignore all major updates updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]