# Specify the timezone for checks

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:37" # hh:mm formate
      timezone: "Australia/Perth"
    open-pull-requests-limit: 1
    milestone: 2
    assignees:
      - "vvsrrSunny"
    reviewers:
     - "vvsrrSunny"
    # ignore:
    #   # ignore all GitHub linguist patch updates
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]